[tool.ruff]
line-length = 120
target-version = "py39"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D", # missing docstrings and formatting
    "ANN", # missing type annotations
    "COM", # trailing commas
    "CPY", # missing copyright notice
    "ISC001", # don't check for implicitly concatenated strings
    "FBT", # bool-typed positional arguments
    "EM", # exceptions must not use string literals
    "TRY003", # long messages outside the exception class
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]

[tool.ruff.lint.isort]
force-single-line = true
force-sort-within-sections = true
order-by-type = false

[tool.ruff.lint.pydocstyle]
convention = "google"
